language: java
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: SDleama82Ol6yYyzOfFVXX0Kd/1gYOi3X3+eBkiD/byUivW/o/m2QSzn4sn2Rk4tQ+0Pap8LqmUhZRSM4CGJVrzejYYqhSDkcXyWcRF2OQ/pTUKI1/X36AMav9It4LggLtRptTYjk0RPJ6ZpqQ64TH4xIm0aiuJvnlnvimxOdYZJEROg/k2mlFHAeEl8eKcGZHc0e0/YkD5skxLfpkuBYrZkNAN0fIOayMRKes5pp3IoeGXs9KYZvsG1AOW12bzkUj3YbIRCmK32f0kvy0FKEufI5erF8K9KeiU1sHf9UQcixEIlqXt+X7AqQ1i2U3KngHV7wOt9dGz7PkYm/O5TxhuVnr+mMrEmGs9NRvhD8N8dBH2SPitxqR4U/kCbcABOi2K6i/CqsKkTUGjYaLaLoGB+lHADAokgccsu+Z1yzqg9mZ96Km3cuIBEzJnEt23Y35wsO4lo3YziaC6EGvB8PAoNRa4hBwounKkqPo3RMKgT0Ysd87RQ/ONF5AQi8NLD1EE5/aJSUvqMbAisJOS/vUJIJg959m0rF1qfMQjECZ0k1sWYLIv4n5lBFaLY/rD7/wpKXgY6Ap8/W9Zj/XXi7J/dzHcnezBqJ6YJyCPmS6LPBXMtK7NcLk225ZJX61q+quVivmFLw3mi821Hjb+OuGprKynCtAhvqS1n/LKXzf8=
  app: exercise-demo
