language: java
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Gu2fqRBnBqBsCviBvOO3GuiSuUm+Uc5bZwvCpApN8dqEbLs4OqNQ9w4XTU8iPWRSlb/AnrgWI5StUsCl6RIQySfQmWZyxgc158ZSyxo6VwEAF+nDzN7F5LWvP6EG/2rTiggMiSI7j/xKyy6S++3q4De18CmgVIPdfDO3AmJm2jsKODWKgm2/bjTNQelcwmA07zh9xriSBbfVLUtUnO8iUtJRb1KJGsQkKOeY6DXka71U3QxWsRwg03MM+Ko8r9S5cI57JCB5eq6L7aNDe3tux9hh4K4a/k4UQtW74XM3Ul3mYgHgcL0Fn9hgZ8a3YfnTFHEWXEtECxMr6t8ChMjG5OWbUZL774RB7USPaTlPQ5c60O4iIBpbxNpHgixFMB8HlFs1du1V0Alq7RKIi63minBtR58l8m8SKNbR+mfhyDfhcUj92Hz/N2vw02SgK2o7fH6EfwEJ1Q2W8nxtMHGdTLC0oJieBKqXX32jopGhZaBAlT1TL4JkYDhYXVNOyuUhFQsozXcXcyKIAFddXo1qOM5V80kYYlKJnRvTpbpEU+MIUulzVyI3LxUShCs55U/4wwr4IgcqtfZZYwihiur9u5kM3dl4WdrNuzFlFnIlx6vZw5FTvEYXGqttdkB2N2VohYtlGHGbRLPaXBwGz00NzJsye2c3PGhrGD/dkMBJXbU=
  app: exercise-demo
